<template>
  <Content title="Hello">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis enim at nisi vehicula tempus eu ac metus. Aliquam lacus risus, mollis nec nisi eu, iaculis vehicula est. Quisque varius ornare dolor vitae lacinia. Donec pulvinar ornare tortor, ut vulputate risus dignissim ut. Mauris ornare congue risus vel congue. Vivamus luctus sodales molestie. Etiam a ullamcorper tellus. Cras id commodo tellus. Etiam pulvinar, metus nec vestibulum eleifend, ligula ante rhoncus purus, a mollis ipsum lorem at massa. Donec libero sem, egestas ac est a, aliquam ultrices sem. Aenean nec iaculis magna, quis fringilla neque. Phasellus feugiat, purus id aliquet volutpat, urna purus sodales nibh, vitae imperdiet purus dolor in lectus. Nam dictum in sem a rhoncus. Aliquam commodo vel lorem vitae maximus. Aenean iaculis sagittis orci a lacinia. Proin egestas aliquet risus eu dictum.

Duis quis turpis a risus blandit maximus at sit amet erat. Ut ac facilisis augue. Sed gravida a lacus ut maximus. Praesent at posuere velit, at dictum ex. Cras viverra velit vel libero tincidunt convallis. Quisque eget laoreet massa, id posuere nunc. Integer id eros tincidunt, euismod nunc vel, hendrerit erat. Aenean gravida nulla vitae fringilla consectetur.

Proin pulvinar rutrum nisi sit amet lobortis. Curabitur bibendum turpis tristique leo euismod, eget mattis sem porttitor. Curabitur fermentum ex dui, vitae euismod elit iaculis ut. Proin sit amet varius orci, in egestas odio. Donec in hendrerit leo. Nulla rutrum molestie urna, id molestie urna ultrices vitae. Duis ultricies elementum nisl id aliquam. Aenean non pulvinar risus. Pellentesque sit amet ullamcorper massa. In egestas, magna fermentum aliquet volutpat, eros ipsum pulvinar lectus, vel convallis dolor mauris nec turpis. Integer interdum posuere porta. Vivamus dignissim purus ac enim viverra, sit amet mattis augue iaculis. Ut eu tincidunt justo. Vivamus interdum dolor ac ipsum ullamcorper aliquam. Morbi mollis quam et condimentum tempor. Suspendisse ipsum mauris, viverra id porttitor id, ultricies at magna.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus pretium nibh est, porta rhoncus augue mollis quis. Fusce pretium, dui sit amet eleifend vestibulum, metus augue laoreet erat, eget dapibus velit velit sed diam. Cras iaculis lectus tellus, a faucibus risus pharetra vel. Pellentesque quis velit euismod, pulvinar dui pharetra, pretium lectus. Morbi id justo nunc. Morbi iaculis turpis nec mauris aliquam fringilla. Proin luctus pharetra facilisis. Etiam auctor metus a scelerisque dapibus. Nullam in iaculis ante. Nunc rhoncus augue nec ullamcorper elementum.

Cras sed aliquam augue. Integer ullamcorper accumsan ipsum, vitae iaculis purus blandit in. Fusce maximus odio at odio ultricies, sagittis mollis lacus pellentesque. Fusce et ex mauris. Morbi vel accumsan tellus. Fusce mattis ante eget ex sagittis convallis. Sed nunc justo, blandit et nisi sed, vehicula imperdiet tortor. Suspendisse sit amet nisl quis leo sagittis sollicitudin. Nunc finibus eu libero in euismod. Donec fermentum, erat non imperdiet malesuada, felis dolor consequat nulla, in sagittis sem enim egestas erat. Sed ornare lobortis sapien quis dictum. Vestibulum tempus gravida nulla, quis scelerisque ex. Nam efficitur nec diam ac egestas. Aliquam erat volutpat. Aliquam finibus faucibus tortor, non varius quam.</p>
  </Content>
</template>

<script setup lang="ts">
import Content from '../components/Content.vue';
</script>
